import { EventType } from "@/components/profile/profile-events-cards";

export const EVENTS_DATA: EventType[] = [
    {
        id: 1,
        title: "UX/UI Design Sprint",
        description: "A fast-paced collaborative session to wireframe, prototype, and test user interface concepts together.",
        category: "Meetings",
        categoryId: 4,
        members: "8/10",
        colorFrom: "from-brand-purple",
        colorTo: "to-[#C4B5FD]",
        image: "https://images.unsplash.com/photo-1531403009284-440f080d1e12?q=80&w=500&auto=format&fit=crop",
        location: "Buenos Aires",
        startDate: "2026-10-15T10:00:00Z",
        owner: "Alex S.",
        ownerUsername: "Alexeque1",
        ownerId: 1,
        adminIds: [10],
        role: "owner",
        createdAt: "2026-09-01T10:00:00Z",
    },
    {
        id: 2,
        title: "Weekend Hikers BA",
        description: "Explore scenic nature trails around the outskirts of the city and enjoy fresh air with fellow outdoor enthusiasts.",
        category: "Nature",
        categoryId: 3,
        members: "15/20",
        colorFrom: "from-brand-green",
        colorTo: "to-[#34D399]",
        image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=500&auto=format&fit=crop",
        location: "Córdoba",
        startDate: "2026-10-22T08:00:00Z",
        owner: "Maria G.",
        ownerUsername: "Maria123",
        ownerId: 2,
        adminIds: [1, 9],
        role: "admin",
        createdAt: "2026-09-05T11:30:00Z",
    },
    {
        id: 3,
        title: "Techno Warehouse Party",
        description: "An immersive electronic music gathering featuring underground local DJs and state-of-the-art light shows.",
        category: "Party",
        categoryId: 1,
        members: "120/150",
        colorFrom: "from-pink-500",
        colorTo: "to-pink-300",
        image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?q=80&w=500&auto=format&fit=crop",
        location: "Rosario",
        startDate: "2026-10-31T23:30:00Z",
        owner: "Alex S.",
        ownerUsername: "Alexeque1",
        ownerId: 1,
        adminIds: [3],
        role: "owner",
        createdAt: "2026-09-10T14:20:00Z",
    },
    {
        id: 4,
        title: "Indie Rock Night",
        description: "Live independent music showcase celebrating the best underground guitar bands and alt-rock anthems.",
        category: "Concerts",
        categoryId: 2,
        members: "45/50",
        colorFrom: "from-brand-purple-deep",
        colorTo: "to-[#A78BFA]",
        image: "https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?q=80&w=500&auto=format&fit=crop",
        location: "Buenos Aires",
        startDate: "2026-11-05T21:00:00Z",
        owner: "Lucas R.",
        ownerUsername: "LucasRock",
        ownerId: 3,
        adminIds: [2, 8],
        role: "member",
        createdAt: "2026-09-12T09:15:00Z",
    },
    {
        id: 5,
        title: "Specialty Coffee Tasting",
        description: "An intimate gathering to sample single-origin beans, learn brewing techniques, and discuss flavor notes.",
        category: "Hobbies",
        categoryId: 5,
        members: "5/5",
        colorFrom: "from-brand-peach",
        colorTo: "to-brand-orange",
        image: "https://images.unsplash.com/photo-1511920170033-f8396924c348?q=80&w=500&auto=format&fit=crop",
        location: "Buenos Aires",
        startDate: "2026-11-12T16:00:00Z",
        owner: "Lucía P.",
        ownerUsername: "LucyCoffee",
        ownerId: 4,
        adminIds: [],
        role: "member",
        createdAt: "2026-09-14T16:45:00Z",
    },
    {
        id: 6,
        title: "Startup Founders Meetup",
        description: "Networking event for entrepreneurs, innovators, and creators to share ideas, pitch projects, and find collaborators.",
        category: "Meetings",
        categoryId: 4,
        members: "28/30",
        colorFrom: "from-brand-purple-deep",
        colorTo: "to-brand-purple",
        image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=500&auto=format&fit=crop",
        location: "Mendoza",
        startDate: "2026-10-25T18:30:00Z",
        owner: "Alex S.",
        ownerUsername: "Alexeque1",
        ownerId: 1,
        adminIds: [10],
        role: "owner",
        createdAt: "2026-09-15T12:00:00Z",
    },
    {
        id: 7,
        title: "Sunset Rooftop Party",
        description: "Good music, drinks, and networking as the sun goes down over the city skyline from a high-rise terrace.",
        category: "Party",
        categoryId: 1,
        members: "50/50",
        colorFrom: "from-amber-500",
        colorTo: "to-amber-200",
        image: "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?q=80&w=500&auto=format&fit=crop",
        location: "Buenos Aires",
        startDate: "2026-11-18T19:00:00Z",
        owner: "Camila R.",
        ownerUsername: "CamiR",
        ownerId: 5,
        adminIds: [],
        role: "member",
        createdAt: "2026-09-08T18:30:00Z",
    },
    {
        id: 8,
        title: "Functional Cross Training",
        description: "High-intensity group workout focused on agility, strength, and core conditioning in an outdoor park setting.",
        category: "Fitness",
        categoryId: 6,
        members: "10/12",
        colorFrom: "from-brand-mint",
        colorTo: "to-brand-green",
        image: "https://images.unsplash.com/photo-1554284126-aa88f22d8b74?q=80&w=500&auto=format&fit=crop",
        location: "La Plata",
        startDate: "2026-10-20T17:30:00Z",
        owner: "Julián P.",
        ownerUsername: "JuliFit",
        ownerId: 6,
        adminIds: [12],
        role: "admin",
        createdAt: "2026-09-12T08:00:00Z",
    },
    {
        id: 9,
        title: "Salsa & Bachata Social",
        description: "An energetic evening of Latin dance instruction, social dancing, and rhythm practice for all skill levels.",
        category: "Party",
        categoryId: 1,
        members: "60/80",
        colorFrom: "from-rose-500",
        colorTo: "to-orange-300",
        image: "https://images.unsplash.com/photo-1508807526345-15e9b5f4eaff?q=80&w=500&auto=format&fit=crop",
        location: "Rosario",
        startDate: "2026-11-21T22:00:00Z",
        owner: "Sofía M.",
        ownerUsername: "SofiDance",
        ownerId: 7,
        adminIds: [5],
        createdAt: "2026-09-14T15:10:00Z",
    },
    {
        id: 10,
        title: "Jazz Trio Live Session",
        description: "A cozy acoustic performance featuring talented local jazz improvisers in an intimate lounge atmosphere.",
        category: "Concerts",
        categoryId: 2,
        members: "35/40",
        colorFrom: "from-indigo-600",
        colorTo: "to-violet-300",
        image: "https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?q=80&w=500&auto=format&fit=crop",
        location: "Buenos Aires",
        startDate: "2026-12-01T21:30:00Z",
        owner: "Diego F.",
        ownerUsername: "DiegoJazz",
        ownerId: 8,
        adminIds: [],
        createdAt: "2026-09-16T20:00:00Z",
    },
    {
        id: 11,
        title: "Patagonia Trekking Club",
        description: "Advanced expedition hiking through rugged southern mountain paths and breathtaking glacial valleys.",
        category: "Nature",
        categoryId: 3,
        members: "18/25",
        colorFrom: "from-teal-600",
        colorTo: "to-emerald-300",
        image: "https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?q=80&w=500&auto=format&fit=crop",
        location: "Bariloche",
        startDate: "2026-12-10T07:00:00Z",
        owner: "Martín L.",
        ownerUsername: "MartiTrek",
        ownerId: 9,
        adminIds: [],
        createdAt: "2026-09-17T09:30:00Z",
    },
    {
        id: 12,
        title: "Product Management Circle",
        description: "Peer discussion group tackling product roadmaps, user metrics, agile frameworks, and case studies.",
        category: "Meetings",
        categoryId: 4,
        members: "22/40",
        colorFrom: "from-blue-600",
        colorTo: "to-sky-300",
        image: "https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=500&auto=format&fit=crop",
        location: "Buenos Aires",
        startDate: "2026-11-08T18:00:00Z",
        owner: "Valentina O.",
        ownerUsername: "ValePM",
        ownerId: 10,
        adminIds: [],
        createdAt: "2026-09-10T11:00:00Z",
    },
    {
        id: 13,
        title: "Board Games Night",
        description: "A fun tabletop session exploring strategy games, cooperative quests, and classic party game nights.",
        category: "Hobbies",
        categoryId: 5,
        members: "12/16",
        colorFrom: "from-amber-600",
        colorTo: "to-yellow-300",
        image: "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?q=80&w=500&auto=format&fit=crop",
        location: "La Plata",
        startDate: "2026-10-28T19:30:00Z",
        owner: "Nicolás V.",
        ownerUsername: "NicoBoard",
        ownerId: 11,
        adminIds: [],
        createdAt: "2026-09-12T14:15:00Z",
    },
    {
        id: 14,
        title: "Sunrise Yoga & Pilates",
        description: "Mindful stretching, balance training, and breathing exercises designed to center your body and mind at dawn.",
        category: "Fitness",
        categoryId: 6,
        members: "14/20",
        colorFrom: "from-rose-400",
        colorTo: "to-pink-200",
        image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?q=80&w=500&auto=format&fit=crop",
        location: "Mar del Plata",
        startDate: "2026-11-15T06:30:00Z",
        owner: "Florencia T.",
        ownerUsername: "FloYoga",
        ownerId: 12,
        adminIds: [6],
        createdAt: "2026-09-14T07:45:00Z",
    },
    {
        id: 15,
        title: "Craft Beer Tasting Club",
        description: "Sample unique microbrews, learn about fermentation profiles, and meet local brewing masters.",
        category: "Hobbies",
        categoryId: 5,
        members: "20/20",
        colorFrom: "from-orange-600",
        colorTo: "to-amber-300",
        image: "https://images.unsplash.com/photo-1608270586620-248524c67de9?q=80&w=500&auto=format&fit=crop",
        location: "Córdoba",
        startDate: "2026-11-25T20:00:00Z",
        owner: "Ignacio D.",
        ownerUsername: "NachoBeer",
        ownerId: 13,
        adminIds: [],
        createdAt: "2026-09-02T19:00:00Z",
    },
    {
        id: 16,
        title: "Open Mic Comedy Night",
        description: "A hilarious evening of stand-up routines, raw humor, and comedic performances from emerging local acts.",
        category: "Concerts",
        categoryId: 2,
        members: "70/100",
        colorFrom: "from-fuchsia-600",
        colorTo: "to-purple-300",
        image: "https://images.unsplash.com/photo-1585699324551-f6c309eedeca?q=80&w=500&auto=format&fit=crop",
        location: "Mendoza",
        startDate: "2026-12-05T21:00:00Z",
        owner: "Camila R.",
        ownerUsername: "CamiR",
        ownerId: 5,
        adminIds: [],
        createdAt: "2026-09-08T13:20:00Z",
    }
];