import { GroupType } from "@/components/profile/profile-groups-cards";

export const GROUPS_DATA: GroupType[] = [
    {
        id: 1,
        title: "UX/UI Design Sprint",
        description: "A fast-paced collaborative session to wireframe, prototype, and test user interface concepts together.",
        category: "Meetings",
        categoryId: 4,
        members: "8/10",
        colorFrom: "from-[#8C6CFF]",
        colorTo: "to-[#C4B5FD]",
        image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?q=80&w=500&auto=format&fit=crop",
        location: "Buenos Aires",
        startDate: "Aug 2, 2026",
        owner: "Alex S.",
        ownerUsername: "Alexeque1",
        ownerId: 1,
        adminIds: [10], // Valentina Ortiz
        role: "owner",
        status: "Upcoming",
        statusClasses: "bg-[#8C6CFF]/20 text-[#6D28D9] border-[#8C6CFF]/30",
        createdAt: "2026-07-01T10:00:00Z",
    },
    {
        id: 2,
        title: "Weekend Hikers BA",
        description: "Explore scenic nature trails around the outskirts of the city and enjoy fresh air with fellow outdoor enthusiasts.",
        category: "Nature",
        categoryId: 3,
        members: "15/20",
        colorFrom: "from-[#059669]",
        colorTo: "to-[#34D399]",
        image: "https://images.unsplash.com/photo-1551632811-561732d1e306?q=80&w=500&auto=format&fit=crop",
        location: "Córdoba",
        startDate: "Aug 15, 2026",
        owner: "Maria G.",
        ownerUsername: "Maria123",
        ownerId: 2,
        adminIds: [1, 9], // Alex Sequera, Martín López
        role: "admin",
        status: "Active",
        statusClasses: "bg-[#059669]/20 text-[#059669] border-[#059669]/30",
        createdAt: "2026-07-03T11:30:00Z",
    },
    {
        id: 3,
        title: "Techno Warehouse Party",
        description: "An immersive electronic music gathering featuring underground local DJs and state-of-the-art light shows.",
        category: "Party",
        categoryId: 1,
        members: "120/150",
        colorFrom: "from-pink-500",
        colorTo: "to-pink-300",
        image: "https://images.unsplash.com/photo-1574421187333-149301889984?q=80&w=500&auto=format&fit=crop",
        location: "Rosario",
        startDate: "Jul 28, 2026",
        owner: "Alex S.",
        ownerUsername: "Alexeque1",
        ownerId: 1,
        adminIds: [3], // Lucas Rodriguez
        role: "owner",
        status: "Past",
        statusClasses: "bg-black/10 text-black/60 border-black/10",
        createdAt: "2026-06-15T14:20:00Z",
    },
    {
        id: 4,
        title: "Indie Rock Night",
        description: "Live independent music showcase celebrating the best underground guitar bands and alt-rock anthems.",
        category: "Concerts",
        categoryId: 2,
        members: "45/50",
        colorFrom: "from-[#6D28D9]",
        colorTo: "to-[#A78BFA]",
        image: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?q=80&w=500&auto=format&fit=crop",
        location: "Buenos Aires",
        startDate: "Sep 10, 2026",
        owner: "Lucas R.",
        ownerUsername: "LucasRock",
        ownerId: 3,
        adminIds: [2, 8], // Maria Garcia, Diego Fernández
        role: "member",
        status: "Upcoming",
        statusClasses: "bg-[#8C6CFF]/20 text-[#6D28D9] border-[#8C6CFF]/30",
        createdAt: "2026-07-05T09:15:00Z",
    },
    {
        id: 5,
        title: "Specialty Coffee Tasting",
        description: "An intimate gathering to sample single-origin beans, learn brewing techniques, and discuss flavor notes.",
        category: "Hobbies",
        categoryId: 5,
        members: "5/5",
        colorFrom: "from-[#FFB199]",
        colorTo: "to-[#EA580C]",
        image: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?q=80&w=500&auto=format&fit=crop",
        location: "Buenos Aires",
        startDate: "Aug 20, 2026",
        owner: "Lucía P.",
        ownerUsername: "LucyCoffee",
        ownerId: 4,
        adminIds: [],
        role: "member",
        status: "Active",
        statusClasses: "bg-[#059669]/20 text-[#059669] border-[#059669]/30",
        createdAt: "2026-07-08T16:45:00Z",
    },
    {
        id: 6,
        title: "Startup Founders Meetup",
        description: "Networking event for entrepreneurs, innovators, and creators to share ideas, pitch projects, and find collaborators.",
        category: "Meetings",
        categoryId: 4,
        members: "28/30",
        colorFrom: "from-[#6D28D9]",
        colorTo: "to-[#8C6CFF]",
        image: "https://images.unsplash.com/photo-1515187029135-18ee286d815b?q=80&w=500&auto=format&fit=crop",
        location: "Mendoza",
        startDate: "Sep 5, 2026",
        owner: "Alex S.",
        ownerUsername: "Alexeque1",
        ownerId: 1,
        adminIds: [10], // Valentina Ortiz
        role: "owner",
        status: "Upcoming",
        statusClasses: "bg-[#8C6CFF]/20 text-[#6D28D9] border-[#8C6CFF]/30",
        createdAt: "2026-07-10T12:00:00Z",
    },
    {
        id: 7,
        title: "Sunset Rooftop Party",
        description: "Good music, drinks, and networking as the sun goes down over the city skyline from a high-rise terrace.",
        category: "Party",
        categoryId: 1,
        members: "50/50",
        colorFrom: "from-amber-500",
        colorTo: "to-amber-200",
        image: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=500&auto=format&fit=crop",
        location: "Buenos Aires",
        startDate: "Jul 15, 2026",
        owner: "Camila R.",
        ownerUsername: "CamiR",
        ownerId: 5,
        adminIds: [],
        role: "member",
        status: "Past",
        statusClasses: "bg-black/10 text-black/60 border-black/10",
        createdAt: "2026-06-01T18:30:00Z",
    },
    {
        id: 8,
        title: "Functional Cross Training",
        description: "High-intensity group workout focused on agility, strength, and core conditioning in an outdoor park setting.",
        category: "Fitness",
        categoryId: 6,
        members: "10/12",
        colorFrom: "from-[#A9FFD7]",
        colorTo: "to-[#059669]",
        image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?q=80&w=500&auto=format&fit=crop",
        location: "La Plata",
        startDate: "Aug 28, 2026",
        owner: "Julián P.",
        ownerUsername: "JuliFit",
        ownerId: 6,
        adminIds: [12], // Florencia Torres
        role: "admin",
        status: "Upcoming",
        statusClasses: "bg-[#8C6CFF]/20 text-[#6D28D9] border-[#8C6CFF]/30",
        createdAt: "2026-07-12T08:00:00Z",
    },
    {
        id: 9,
        title: "Salsa & Bachata Social",
        description: "An energetic evening of Latin dance instruction, social dancing, and rhythm practice for all skill levels.",
        category: "Party",
        categoryId: 1,
        members: "60/80",
        colorFrom: "from-rose-500",
        colorTo: "to-orange-300",
        image: "https://images.unsplash.com/photo-1504609773096-104ff2c73ba4?q=80&w=500&auto=format&fit=crop",
        location: "Rosario",
        startDate: "Aug 22, 2026",
        owner: "Sofía M.",
        ownerUsername: "SofiDance",
        ownerId: 7,
        adminIds: [5], // Camila Ríos
        status: "Upcoming",
        statusClasses: "bg-[#8C6CFF]/20 text-[#6D28D9] border-[#8C6CFF]/30",
        createdAt: "2026-07-14T15:10:00Z",
    },
    {
        id: 10,
        title: "Jazz Trio Live Session",
        description: "A cozy acoustic performance featuring talented local jazz improvisers in an intimate lounge atmosphere.",
        category: "Concerts",
        categoryId: 2,
        members: "35/40",
        colorFrom: "from-indigo-600",
        colorTo: "to-violet-300",
        image: "https://images.unsplash.com/photo-1511192336575-5a79af67a629?q=80&w=500&auto=format&fit=crop",
        location: "Buenos Aires",
        startDate: "Sep 12, 2026",
        owner: "Diego F.",
        ownerUsername: "DiegoJazz",
        ownerId: 8,
        adminIds: [],
        status: "Upcoming",
        statusClasses: "bg-[#8C6CFF]/20 text-[#6D28D9] border-[#8C6CFF]/30",
        createdAt: "2026-07-16T20:00:00Z",
    },
    {
        id: 11,
        title: "Patagonia Trekking Club",
        description: "Advanced expedition hiking through rugged southern mountain paths and breathtaking glacial valleys.",
        category: "Nature",
        categoryId: 3,
        members: "18/25",
        colorFrom: "from-teal-600",
        colorTo: "to-emerald-300",
        image: "https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?q=80&w=500&auto=format&fit=crop",
        location: "Bariloche",
        startDate: "Sep 20, 2026",
        owner: "Martín L.",
        ownerUsername: "MartiTrek",
        ownerId: 9,
        adminIds: [],
        status: "Upcoming",
        statusClasses: "bg-[#8C6CFF]/20 text-[#6D28D9] border-[#8C6CFF]/30",
        createdAt: "2026-07-18T09:30:00Z",
    },
    {
        id: 12,
        title: "Product Management Circle",
        description: "Peer discussion group tackling product roadmaps, user metrics, agile frameworks, and case studies.",
        category: "Meetings",
        categoryId: 4,
        members: "22/40",
        colorFrom: "from-blue-600",
        colorTo: "to-sky-300",
        image: "https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=500&auto=format&fit=crop",
        location: "Buenos Aires",
        startDate: "Aug 18, 2026",
        owner: "Valentina O.",
        ownerUsername: "ValePM",
        ownerId: 10,
        adminIds: [],
        status: "Active",
        statusClasses: "bg-[#059669]/20 text-[#059669] border-[#059669]/30",
        createdAt: "2026-07-20T11:00:00Z",
    },
    {
        id: 13,
        title: "Board Games Night",
        description: "A fun tabletop session exploring strategy games, cooperative quests, and classic party game nights.",
        category: "Hobbies",
        categoryId: 5,
        members: "12/16",
        colorFrom: "from-amber-600",
        colorTo: "to-yellow-300",
        image: "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?q=80&w=500&auto=format&fit=crop",
        location: "La Plata",
        startDate: "Aug 25, 2026",
        owner: "Nicolás V.",
        ownerUsername: "NicoBoard",
        ownerId: 11,
        adminIds: [],
        status: "Upcoming",
        statusClasses: "bg-[#8C6CFF]/20 text-[#6D28D9] border-[#8C6CFF]/30",
        createdAt: "2026-07-22T14:15:00Z",
    },
    {
        id: 14,
        title: "Sunrise Yoga & Pilates",
        description: "Mindful stretching, balance training, and breathing exercises designed to center your body and mind at dawn.",
        category: "Fitness",
        categoryId: 6,
        members: "14/20",
        colorFrom: "from-rose-400",
        colorTo: "to-pink-200",
        image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?q=80&w=500&auto=format&fit=crop",
        location: "Mar del Plata",
        startDate: "Sep 1, 2026",
        owner: "Florencia T.",
        ownerUsername: "FloYoga",
        ownerId: 12,
        adminIds: [6], // Julián Paz
        status: "Upcoming",
        statusClasses: "bg-[#8C6CFF]/20 text-[#6D28D9] border-[#8C6CFF]/30",
        createdAt: "2026-07-24T07:45:00Z",
    },
    {
        id: 15,
        title: "Craft Beer Tasting Club",
        description: "Sample unique microbrews, learn about fermentation profiles, and meet local brewing masters.",
        category: "Hobbies",
        categoryId: 5,
        members: "20/20",
        colorFrom: "from-orange-600",
        colorTo: "to-amber-300",
        image: "https://images.unsplash.com/photo-1608270586620-248524c67de9?q=80&w=500&auto=format&fit=crop",
        location: "Córdoba",
        startDate: "Jul 20, 2026",
        owner: "Ignacio D.",
        ownerUsername: "NachoBeer",
        ownerId: 13,
        adminIds: [],
        status: "Past",
        statusClasses: "bg-black/10 text-black/60 border-black/10",
        createdAt: "2026-06-25T19:00:00Z",
    },
    {
        id: 16,
        title: "Open Mic Comedy Night",
        description: "A hilarious evening of stand-up routines, raw humor, and comedic performances from emerging local acts.",
        category: "Concerts",
        categoryId: 2,
        members: "70/100",
        colorFrom: "from-fuchsia-600",
        colorTo: "to-purple-300",
        image: "https://images.unsplash.com/photo-1517457373958-b7bdd4587205?q=80&w=500&auto=format&fit=crop",
        location: "Mendoza",
        startDate: "Sep 6, 2026",
        owner: "Camila R.",
        ownerUsername: "CamiR",
        ownerId: 5,
        adminIds: [],
        status: "Upcoming",
        statusClasses: "bg-[#8C6CFF]/20 text-[#6D28D9] border-[#8C6CFF]/30",
        createdAt: "2026-07-26T13:20:00Z",
    }
];