export interface UserGroups {
    owner: number[]; 
    admin: number[];
    member: number[]; 
}

export interface UserType {
    id: number;
    firstName: string;
    lastName: string;
    username: string;
    profileImage: string;
    groups: UserGroups;
    communityIds: number[]; // IDs de las comunidades a las que pertenece
    friendIds: number[];    // IDs de sus amigos
    bio: string;
    city: string;
    country: string;
    profession: string;
    languages: string[];
    interests: string[];
    joined: string; // Mes y año de registro, ej: "October 2023"
}

export type FeedUser = Pick<UserType, "firstName" | "lastName" | "username" | "profileImage">;

export const USERS_DATA: UserType[] = [
    {
        id: 1,
        firstName: "Alexander",
        lastName: "Sequera",
        username: "Alexeque1",
        profileImage: "/profile-image.png",
        groups: {
            owner: [1, 3, 6],
            admin: [2],
            member: [4],
        },
        communityIds: [1, 2, 3],
        friendIds: [14, 15, 16, 17, 18, 19],
        bio: "A lover of technology, live music, and good coffee. Always seeking new adventures and groups to share interests with.",
        city: "Buenos Aires",
        country: "Argentina",
        profession: "UX/UI Designer",
        languages: ["English", "Spanish"],
        interests: ["Technology", "Live Music", "Coffee", "Design"],
        joined: "October 2023",
    },
    {
        id: 2,
        firstName: "Maria",
        lastName: "Garcia",
        username: "Maria123",
        profileImage: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=500&auto=format&fit=crop",
        groups: {
            owner: [2],
            admin: [4],
            member: [1],
        },
        communityIds: [1, 3],
        friendIds: [14, 16],
        bio: "Passionate about outdoor adventures and connecting with new communities every weekend.",
        city: "Córdoba",
        country: "Argentina",
        profession: "Marketing Specialist",
        languages: ["Spanish", "Portuguese"],
        interests: ["Outdoor Adventures", "Marketing", "Travel"],
        joined: "January 2024",
    },
    {
        id: 3,
        firstName: "Lucas",
        lastName: "Rodriguez",
        username: "LucasRock",
        profileImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=500&auto=format&fit=crop",
        groups: {
            owner: [4],
            admin: [3],
            member: [1, 2],
        },
        communityIds: [2],
        friendIds: [15, 17],
        bio: "Techno head and weekend DJ, always chasing the next warehouse party.",
        city: "Rosario",
        country: "Argentina",
        profession: "Sound Engineer",
        languages: ["Spanish", "English"],
        interests: ["Techno Music", "DJing", "Nightlife"],
        joined: "March 2024",
    },
    {
        id: 4,
        firstName: "Lucía",
        lastName: "Pérez",
        username: "LucyCoffee",
        profileImage: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=500&auto=format&fit=crop",
        groups: {
            owner: [5],
            admin: [],
            member: [12, 15],
        },
        communityIds: [1, 2, 3],
        friendIds: [],
        bio: "Specialty coffee enthusiast who loves slow mornings and good conversation.",
        city: "Mendoza",
        country: "Argentina",
        profession: "Barista & Coffee Roaster",
        languages: ["Spanish"],
        interests: ["Coffee", "Slow Living", "Conversation"],
        joined: "February 2024",
    },
    {
        id: 5,
        firstName: "Camila",
        lastName: "Ríos",
        username: "CamiR",
        profileImage: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=500&auto=format&fit=crop",
        groups: {
            owner: [7, 16],
            admin: [9],
            member: [1, 8],
        },
        communityIds: [1],
        friendIds: [18],
        bio: "Organizing unforgettable nights and always looking for the best rooftop in town.",
        city: "Buenos Aires",
        country: "Argentina",
        profession: "Event Planner",
        languages: ["Spanish", "English"],
        interests: ["Event Planning", "Nightlife", "Networking"],
        joined: "November 2023",
    },
    {
        id: 6,
        firstName: "Julián",
        lastName: "Paz",
        username: "JuliFit",
        profileImage: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=500&auto=format&fit=crop",
        groups: {
            owner: [8],
            admin: [14],
            member: [2],
        },
        communityIds: [3],
        friendIds: [17],
        bio: "Fitness coach obsessed with functional training and clean eating.",
        city: "La Plata",
        country: "Argentina",
        profession: "Personal Trainer",
        languages: ["Spanish"],
        interests: ["Fitness", "Nutrition", "Wellness"],
        joined: "December 2023",
    },
    {
        id: 7,
        firstName: "Sofía",
        lastName: "Méndez",
        username: "SofiDance",
        profileImage: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=500&auto=format&fit=crop",
        groups: {
            owner: [9],
            admin: [],
            member: [3, 7],
        },
        communityIds: [1, 2],
        friendIds: [],
        bio: "Salsa and bachata instructor spreading rhythm one class at a time.",
        city: "Rosario",
        country: "Argentina",
        profession: "Dance Instructor",
        languages: ["Spanish", "Italian"],
        interests: ["Dance", "Latin Music", "Teaching"],
        joined: "April 2024",
    },
    {
        id: 8,
        firstName: "Diego",
        lastName: "Fernández",
        username: "DiegoJazz",
        profileImage: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?q=80&w=500&auto=format&fit=crop",
        groups: {
            owner: [10],
            admin: [4],
            member: [13],
        },
        communityIds: [2, 3],
        friendIds: [],
        bio: "Jazz pianist who never turns down a good live session.",
        city: "Buenos Aires",
        country: "Argentina",
        profession: "Musician",
        languages: ["Spanish", "English"],
        interests: ["Jazz", "Piano", "Live Music"],
        joined: "January 2024",
    },
    {
        id: 9,
        firstName: "Martín",
        lastName: "López",
        username: "MartiTrek",
        profileImage: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=500&auto=format&fit=crop",
        groups: {
            owner: [11],
            admin: [2],
            member: [8],
        },
        communityIds: [1],
        friendIds: [15],
        bio: "Mountain guide who spends more time on trails than at home.",
        city: "Bariloche",
        country: "Argentina",
        profession: "Outdoor Guide",
        languages: ["Spanish", "English"],
        interests: ["Hiking", "Nature", "Trekking"],
        joined: "May 2024",
    },
    {
        id: 10,
        firstName: "Valentina",
        lastName: "Ortiz",
        username: "ValePM",
        profileImage: "https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=500&auto=format&fit=crop",
        groups: {
            owner: [12],
            admin: [1, 6],
            member: [5],
        },
        communityIds: [1, 3],
        friendIds: [16, 19],
        bio: "Product manager by day, board game enthusiast by night.",
        city: "Buenos Aires",
        country: "Argentina",
        profession: "Product Manager",
        languages: ["Spanish", "English"],
        interests: ["Product Management", "Board Games", "Strategy"],
        joined: "September 2023",
    },
    {
        id: 11,
        firstName: "Nicolás",
        lastName: "Vargas",
        username: "NicoBoard",
        profileImage: "https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?q=80&w=500&auto=format&fit=crop",
        groups: {
            owner: [13],
            admin: [],
            member: [15, 10],
        },
        communityIds: [2],
        friendIds: [19],
        bio: "Board games collector always looking for the fourth player.",
        city: "La Plata",
        country: "Argentina",
        profession: "Software Engineer",
        languages: ["Spanish", "English"],
        interests: ["Board Games", "Software Development", "Tabletop Gaming"],
        joined: "June 2024",
    },
    {
        id: 12,
        firstName: "Florencia",
        lastName: "Torres",
        username: "FloYoga",
        profileImage: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=500&auto=format&fit=crop",
        groups: {
            owner: [14],
            admin: [8],
            member: [2, 11],
        },
        communityIds: [3],
        friendIds: [18],
        bio: "Certified yoga instructor helping people find balance, one sunrise class at a time.",
        city: "Mar del Plata",
        country: "Argentina",
        profession: "Yoga Instructor",
        languages: ["Spanish"],
        interests: ["Yoga", "Mindfulness", "Wellness"],
        joined: "July 2024",
    },
    {
        id: 13,
        firstName: "Ignacio",
        lastName: "Díaz",
        username: "NachoBeer",
        profileImage: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=500&auto=format&fit=crop",
        groups: {
            owner: [15],
            admin: [],
            member: [13, 7],
        },
        communityIds: [1, 2],
        friendIds: [14, 15],
        bio: "Craft beer nerd who's always fermenting something new.",
        city: "Córdoba",
        country: "Argentina",
        profession: "Homebrewer",
        languages: ["Spanish", "German"],
        interests: ["Craft Beer", "Brewing", "Tasting"],
        joined: "August 2024",
    },

    // --- NUEVOS USUARIOS: LA LISTA DE AMIGOS DE ALEXANDER (IDs 14 al 19) ---
    {
        id: 14,
        firstName: "Sofía",
        lastName: "Martínez",
        username: "sofiam",
        profileImage: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=200&auto=format&fit=crop",
        groups: { owner: [], admin: [], member: [2, 4] },
        communityIds: [1, 3],
        friendIds: [1, 2, 13, 15], // El 1 es Alex; 15 (Lucas) es amigo en común con Alex
        bio: "Creative soul with a love for design, music festivals, and travel.",
        city: "Buenos Aires",
        country: "Argentina",
        profession: "Graphic Designer",
        languages: ["Spanish", "English"],
        interests: ["Design", "Music Festivals", "Travel"],
        joined: "October 2023",
    },
    {
        id: 15,
        firstName: "Lucas",
        lastName: "Pereira",
        username: "lucasp",
        profileImage: "https://images.unsplash.com/photo-1599566150163-29194dcaad36?q=80&w=200&auto=format&fit=crop",
        groups: { owner: [], admin: [], member: [1, 8] },
        communityIds: [2],
        friendIds: [1, 3, 9, 13, 14], // 14 (Sofía) es amiga en común con Alex
        bio: "Backend developer who spends weekends exploring the city's live music scene.",
        city: "Buenos Aires",
        country: "Argentina",
        profession: "Backend Developer",
        languages: ["Spanish", "English"],
        interests: ["Software Development", "Live Music", "Backend"],
        joined: "November 2023",
    },
    {
        id: 16,
        firstName: "Valentina",
        lastName: "Gómez",
        username: "valegomez",
        profileImage: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=200&auto=format&fit=crop",
        groups: { owner: [], admin: [], member: [6, 12] },
        communityIds: [1, 2, 3],
        friendIds: [1, 2, 10, 17], // 17 (Mateo) es amigo en común con Alex
        bio: "Building communities online and offline, one event at a time.",
        city: "Buenos Aires",
        country: "Argentina",
        profession: "Community Manager",
        languages: ["Spanish", "English", "Portuguese"],
        interests: ["Community Building", "Events", "Social Media"],
        joined: "September 2023",
    },
    {
        id: 17,
        firstName: "Mateo",
        lastName: "Silva",
        username: "mateo_s",
        profileImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200&auto=format&fit=crop",
        groups: { owner: [], admin: [], member: [3, 7] },
        communityIds: [2, 3],
        friendIds: [1, 3, 6, 16], // 16 (Valentina) es amiga en común con Alex
        bio: "Photographer chasing warehouse parties and golden hour light.",
        city: "Rosario",
        country: "Argentina",
        profession: "Photographer",
        languages: ["Spanish"],
        interests: ["Photography", "Nightlife", "Travel"],
        joined: "December 2023",
    },
    {
        id: 18,
        firstName: "Camila",
        lastName: "Ruiz",
        username: "camiruiz",
        profileImage: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=200&auto=format&fit=crop",
        groups: { owner: [], admin: [], member: [14, 16] },
        communityIds: [1, 3],
        friendIds: [1, 5, 12],
        bio: "Illustrator inspired by yoga retreats and stand-up comedy nights.",
        city: "Mendoza",
        country: "Argentina",
        profession: "Illustrator",
        languages: ["Spanish", "English"],
        interests: ["Illustration", "Yoga", "Comedy"],
        joined: "October 2023",
    },
    {
        id: 19,
        firstName: "Nicolás",
        lastName: "Herrera",
        username: "nico_h",
        profileImage: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=200&auto=format&fit=crop",
        groups: { owner: [], admin: [], member: [5, 11] },
        communityIds: [1, 2],
        friendIds: [1, 10, 11],
        bio: "Engineer during the week, hiking guide on weekends.",
        city: "Bariloche",
        country: "Argentina",
        profession: "Civil Engineer",
        languages: ["Spanish"],
        interests: ["Hiking", "Engineering", "Outdoors"],
        joined: "August 2023",
    }
];